// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnGQSXQxJHdSJyaU_GVZSuWqRE8QPUqYw',
    appId: '1:362903486955:web:4f9d95fad57429c3e519ae',
    messagingSenderId: '362903486955',
    projectId: 'study-app-f7ffc',
    authDomain: 'study-app-f7ffc.firebaseapp.com',
    storageBucket: 'study-app-f7ffc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwXETkOHfJA6LJVywDO6B8Im_xR2OlPEE',
    appId: '1:362903486955:android:0ae60588ccc5291ce519ae',
    messagingSenderId: '362903486955',
    projectId: 'study-app-f7ffc',
    storageBucket: 'study-app-f7ffc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9xM7DJ1EwKOu_UD3Saf4LgnJhghgbXes',
    appId: '1:362903486955:ios:84c620d7aba62447e519ae',
    messagingSenderId: '362903486955',
    projectId: 'study-app-f7ffc',
    storageBucket: 'study-app-f7ffc.appspot.com',
    iosClientId:
        '362903486955-0kq05h2bp6dao9io4589frcs9tsdqd8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9xM7DJ1EwKOu_UD3Saf4LgnJhghgbXes',
    appId: '1:362903486955:ios:84c620d7aba62447e519ae',
    messagingSenderId: '362903486955',
    projectId: 'study-app-f7ffc',
    storageBucket: 'study-app-f7ffc.appspot.com',
    iosClientId:
        '362903486955-0kq05h2bp6dao9io4589frcs9tsdqd8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );
}
